name: ParticleText
author: Despical
version: ${project.version}
main: me.despical.particletext.Main
api-version: 1.13
description: Show any text using Minecraft particles
website: https://www.spigotmc.org/resources/110996

permissions:
  pt.*:
    default: op
    children:
      pt.create: true
      pt.delete: true
      pt.list: true
      pt.tp: true
      pt.tphere: true
      pt.particle: true
      pt.enabled: true
      pt.font: true
      pt.reload: true
      pt.help: true
      pt.setsize: true