name: ParticleText
author: Despical
version: ${version}
api-version: 1.13
main: dev.despical.particletext.ParticleTextPlugin
description: Show any text using Minecraft particles.

softdepend:
  - Multiverse-Core
  - SlimeWorldManager
  - SlimeWorldPlugin
  - MultiWorld
  - My_Worlds
  - WorldGuard

permissions:
  pt.*:
    default: op
    children:
      pt.create: true
      pt.delete: true
      pt.list: true
      pt.tp: true
      pt.tphere: true
      pt.particle: true
      pt.enabled: true
      pt.font: true
      pt.reload: true
      pt.help: true
      pt.setsize: true
      pt.rotate: true
      pt.version: true
      pt.tabcompleter: true
